### PR TITLE
Build fake-cucumber as a standalone package

### PR DESCRIPTION
**Pull request by aurelien-reeves**
### 🤔 What's changed?

Builds the module as a standalone package using esbuild

### ⚡️ What's your motivation? 

Suggested by @davidjgoss to prevent issues with dependencies versions
Refs. https://github.com/cucumber/react-components/pull/137#discussion_r848068072

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
- :boom: Breaking change (will cause existing user behaviour to not
  work it did before)

### CODE REVIEW

**Review by davidjgoss — COMMENTED** [review]
Looks good!

I think it might be worthwhile to still run `tsc` separately just to get the declarations so consuming projects still benefit from the types, what do you think?

**Comment by aurelien-reeves** [comment]
> Looks good!
> 
> I think it might be worthwhile to still run `tsc` separately just to get the declarations so consuming projects still benefit from the types, what do you think?

I'll give it a try 👌

**Comment by aurelien-reeves** [comment]
I have just added back the types

Not sure it is actually relevant without the library itself. But if we add back the library, we have to let the dependencies as they were before 🤔

@davidjgoss any though?

**Comment by aurelien-reeves** [comment]
From David:

>if we bundle with cli as the entry point we can no longer use programmatically e.g. how we do in react-components
i think to make this idea work we might need to refactor so the bundle entry point is index.ts and then the cli is a wrapper around that - right now there is quite a bit going on in cli.ts though
for now should we perhaps do a release with dependencies upgraded to solve the immediate problems and then take our time with this?

**Pull request closed without merging**
